version: 2
jobs:
  build:
    working_directory: ~/steamgames
    docker:
      - image: circleci/node:8.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: bash .circleci/setup.sh 
      - add_ssh_keys:
          fingerprints: 
           - "be:83:09:0d:87:90:69:fb:37:b6:78:f3:62:67:e3:24"
      - deploy:
          name: deploy master to heroku
          command: |
              git push heroku master            
              heroku ps:scale web=1
        