version: 2
jobs:
  build:
    working_directory: ~/steamgames
    docker:
      - image: circleci/node:8.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

    deployment:
      staging:
        branch: master
        heroku:
          appname: steam-random
        commands: 
          - git push git@heroku.com:steamgames.git master