version: 2
jobs:
  build:
    working_directory: ~/steamgames
    docker:
      - image: circleci/node:8.0.0
    steps:
      - checkout
      - run:
          name: ls
          command: ls -a
      # - checkout
      - run:
          name: update-npm
          command: npm install -g npm
      - run:
          name: install-npm
          command: sudo npm install
      - run:
          name: install nodemon
          command: sudo npm install -g nodemon
      - run: 
          name: run server
          command: nodemon server.js
deployment:
  staging:
    branch: master
    heroku:
      appname: steam-random